### ISSUE TITLE
Manage SP schema: IDP initiated login support for application URLs

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#183]
We're looking to add functionality into the Manage schema that will allow our application catalog to determine if an application login URL supports IDP-initiated Login. EngineBlock [supports it](https://github.com/OpenConext/OpenConext-engineblock/wiki/IdP-initiated-login), so we were wondering if it'd be something worth contributing to OpenConext. Unfortunately there's no current way of extending the schema since it's stored as a file under `manage-server/files/metadata_configuration/saml20_sp.schema.json` (as opposed to a template that we can modify).

Currently there's a `coin:application_url` metadata attribute that's used for application login URLs. If there was another boolean attribute such as `coin:application_url_supports_idp_init_login` (or similar) to have our application catalog determine if it supports IDP-initiated login, that'd be great.

If not, that's alright, but I thought I'd check to see if it'd be something SURF would be open to.

Thanks!
Andrew

**Comment by thijskh** [comment]
There's basically two issues here:
1. No good way to extend the Manage schemata with local fields.
1. Whether being able to note down support for idp-initiated login is something that's generic enough to have in OpenConext-deploy.

Item 1. is something that I think needs to be addressed in any case, because the schema as-is contains fields that are purely relevant to SURF's business processes and it would be cleaner if we could put them in a local addendum or override. I'm not sure what a good approach would be for that.

I'll definitely say yes to item 2, perfectly fine to add. I'm not sure about the naming: coin:application_url just documents the place where you can find the login button/start the login flow (not always obvious from other aspects of the SP). It's not that url that supports idp-init, but the SP-implementation. Would just call it: `coin:supports_idp_init_login`.

**Comment by precurse** [comment]
Thanks Thijs!  I've opened a pull request for the metadata configuration update.

For the schema with local fields,  I guess there could be a couple of options off the top of my head:

1a.  We could do something similar to the EngineBlock 5.7+ config, where there's an override file under `environments/%env%/files` and it copies that if one exists (otherwise use a default one). 

1b. Somehow turn it into a template file with variables to override it like:
sp_schema_override:
```
"coin:a_new_field":
    type: string
    format: boolean
    info: something something something
```
Item 1a. would definitely be easiest, but if there are upstream OpenConext-deploy schema updates, users would need to manually track this file to bring in updates. 1b would be a slight more amount of work up front, but would allow users to keep updated when, say, [attribute properties](https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/manage-server/files/metadata_configuration/saml20_sp.schema.json#L137) or other sections are updated.

We can help get this implemented if you'd like, since it would be helpful to us in the foreseeable future.

**Comment by oharsta** [comment]
We could use solution 1a, but instead of overriding the schema file we merge them during the startup of the Manage application. Only thing we need is a good naming convention. The schema files are now name XXX.schema.json. If we agree on the convention to name the additional schema file XXX.addendum.json - or something else, but you see my point - then I can merge them when constructing the actual schema's in the Manage codebase. @thijskh and @precurse is this something that would work for you guys?

**Comment by thijskh** [comment]
I think that would be fine for me!

**Comment by oharsta** [comment]
See https://github.com/OpenConext/OpenConext-manage/commit/bc17a4ac6cdfd651f0cc966eb424c3261287c53e#diff-81aa2e9fb8ab70f5402eb26df63eb745. This is the support for merging JSON schema files in OpenConext-manage.

**Comment by thijskh** [comment]
Fixed in said commit
